"""
Domain models for the trading system.

This module defines the core data structures that represent the state
and decisions of the trading system, following the requirements from
`mt5-rewrite-requirements.md`.
"""

import json
from dataclasses import asdict, dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional


class OrderType(Enum):
    """Order type enumeration."""

    BUY = "BUY"
    SELL = "SELL"


class OrderStatus(Enum):
    """Order status enumeration."""

    PENDING = "PENDING"
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class ProtectionStage(Enum):
    """Protection stage enumeration."""

    NONE = 0
    STAGE1 = 1  # Breakeven protection at 1.0 * ATR
    STAGE2 = 2  # Trailing protection at 1.5 * ATR


@dataclass
class MarketSnapshot:
    """
    Market snapshot containing all information needed for decision making.

    Based on requirements section 6: '市场快照与指标要求'
    """

    symbol: str
    timeframe: int  # in minutes, e.g., 5 for M5
    digits: int  # price decimal places
    magic_number: int
    bid: float
    ask: float
    ema_fast: float  # EMA fast value
    ema_slow: float  # EMA slow value
    atr14: float  # ATR(14) value
    spread_points: float  # spread in points
    last_closed_bar_time: datetime  # time of last closed bar

    # Additional fields for strategy calculations
    close: float  # Close price of last closed bar
    open: float  # Open price of last closed bar
    high: float  # High price of last closed bar
    low: float  # Low price of last closed bar
    volume: float  # Volume of last closed bar

    # Historical data for trend calculations
    ema_fast_prev3: Optional[float] = None  # EMA fast 3 bars ago
    ema_slow_prev3: Optional[float] = None  # EMA slow 3 bars ago
    high_prev2: Optional[float] = None  # High 2 bars ago
    high_prev3: Optional[float] = None  # High 3 bars ago
    low_prev2: Optional[float] = None  # Low 2 bars ago
    low_prev3: Optional[float] = None  # Low 3 bars ago

    # Extended metrics for strategy modules (Task 4+)
    median_body_20: Optional[float] = None
    prev3_body_max: Optional[float] = None
    volume_ma_20: Optional[float] = None
    high_20: Optional[float] = None
    low_20: Optional[float] = None

    def __post_init__(self):
        """Validate the market snapshot."""
        if self.bid <= 0:
            raise ValueError(f"Bid price must be positive: {self.bid}")
        if self.ask <= 0:
            raise ValueError(f"Ask price must be positive: {self.ask}")
        if self.ask <= self.bid:
            raise ValueError(f"Ask price ({self.ask}) must be greater than bid ({self.bid})")
        if self.atr14 < 0:
            raise ValueError(f"ATR must be non-negative: {self.atr14}")
        if self.spread_points < 0:
            raise ValueError(f"Spread points must be non-negative: {self.spread_points}")


@dataclass
class SignalDecision:
    """
    Signal decision from a strategy.

    Represents a trading signal generated by a strategy module.
    """

    strategy_name: str
    order_type: OrderType
    entry_price: float  # Recommended entry price
    stop_loss: float  # Initial stop loss
    take_profit: float  # Initial take profit
    atr_value: float  # ATR value used for calculations
    lots: float  # Lot size (from FixedLots)

    # Metadata for logging and debugging
    confidence_score: float = 1.0  # 0.0 to 1.0
    signal_strength: float = 1.0  # Relative strength indicator
    conditions_met: List[str] = field(default_factory=list)  # Which conditions were met

    def __post_init__(self):
        """Validate the signal decision."""
        if self.entry_price <= 0:
            raise ValueError(f"Entry price must be positive: {self.entry_price}")
        if self.lots <= 0:
            raise ValueError(f"Lot size must be positive: {self.lots}")
        if self.atr_value <= 0:
            raise ValueError(f"ATR value must be positive: {self.atr_value}")


@dataclass
class TradeIntent:
    """
    Trade intent ready for execution.

    This is the final decision to execute a trade, after all
    validation and gating has passed.
    """

    signal_decision: SignalDecision
    market_snapshot: MarketSnapshot

    # Execution metadata
    action_id: str  # Unique identifier for this trade attempt
    timestamp: datetime = field(default_factory=datetime.now)

    # Execution parameters
    slippage: int = 30  # Default slippage in points
    comment: str = ""  # Order comment

    def __post_init__(self):
        """Validate the trade intent."""
        if not self.action_id:
            raise ValueError("Action ID cannot be empty")


@dataclass
class ProtectionState:
    """
    Protection state for an active position.

    Based on requirements section 13: '运行时状态持久化要求'
    """

    protection_stage: ProtectionStage = ProtectionStage.NONE
    entry_price: Optional[float] = None
    entry_atr: Optional[float] = None
    highest_close_since_entry: Optional[float] = None
    lowest_close_since_entry: Optional[float] = None
    trailing_active: bool = False

    # Stage-specific data
    stage1_activated_at: Optional[datetime] = None
    stage2_activated_at: Optional[datetime] = None

    def __post_init__(self):
        """Validate the protection state."""
        if self.entry_price is not None and self.entry_price <= 0:
            raise ValueError(f"Entry price must be positive: {self.entry_price}")
        if self.entry_atr is not None and self.entry_atr <= 0:
            raise ValueError(f"Entry ATR must be positive: {self.entry_atr}")


@dataclass
class RuntimeState:
    """
    Runtime state that must be persisted for restart continuity.

    Based on requirements section 13: '运行时状态持久化要求'
    """

    day_key: str  # Server day key in format YYYY.MM.DD
    daily_locked: bool = False
    daily_closed_profit: float = 0.0  # Realized profit for current day
    trades_today: int = 0
    last_entry_bar_time: Optional[datetime] = None

    # Active position state (if any)
    protection_state: ProtectionState = field(default_factory=ProtectionState)

    # Additional state for position management
    entry_price: Optional[float] = None
    entry_atr: Optional[float] = None
    highest_close_since_entry: Optional[float] = None
    lowest_close_since_entry: Optional[float] = None
    trailing_active: bool = False

    # System state
    last_processed_bar_time: Optional[datetime] = None
    position_ticket: Optional[int] = None  # MT5 position ticket

    def __post_init__(self):
        """Validate the runtime state."""
        if not self.day_key:
            raise ValueError("Day key cannot be empty")
        if self.daily_closed_profit < 0:
            # Negative closed profit is possible if trades were losers
            pass  # Allow negative values
        if self.trades_today < 0:
            raise ValueError(f"Trades today cannot be negative: {self.trades_today}")

    def to_dict(self) -> Dict[str, Any]:
        """Convert runtime state to dictionary for serialization."""
        data = asdict(self)

        # Convert datetime objects to ISO format strings
        def convert_value(value: Any) -> Any:
            if isinstance(value, datetime):
                return value.isoformat()
            elif isinstance(value, ProtectionStage):
                return value.value
            elif isinstance(value, ProtectionState):
                return asdict(value)
            elif isinstance(value, Enum):
                return value.value
            else:
                return value

        # Apply conversion recursively
        def convert_dict(d: Dict[str, Any]) -> Dict[str, Any]:
            result = {}
            for key, value in d.items():
                if isinstance(value, dict):
                    result[key] = convert_dict(value)
                elif isinstance(value, list):
                    result[key] = [convert_value(item) for item in value]
                else:
                    result[key] = convert_value(value)
            return result

        return convert_dict(data)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "RuntimeState":
        """Create runtime state from dictionary (deserialization)."""

        # Convert string dates back to datetime objects
        def convert_value(key: str, value: Any) -> Any:
            if key in [
                "last_entry_bar_time",
                "last_processed_bar_time",
                "stage1_activated_at",
                "stage2_activated_at",
            ]:
                if value and isinstance(value, str):
                    try:
                        return datetime.fromisoformat(value)
                    except (ValueError, AttributeError):
                        return None
            elif key == "protection_stage" and value is not None:
                return ProtectionStage(value)
            elif key == "protection_state" and isinstance(value, dict):
                # Handle nested ProtectionState
                protection_data = value.copy()
                if "protection_stage" in protection_data:
                    protection_data["protection_stage"] = ProtectionStage(
                        protection_data["protection_stage"]
                    )
                # Convert nested datetime fields
                if "stage1_activated_at" in protection_data:
                    stage1_value = protection_data["stage1_activated_at"]
                    if stage1_value and isinstance(stage1_value, str):
                        try:
                            protection_data["stage1_activated_at"] = datetime.fromisoformat(
                                stage1_value
                            )
                        except (ValueError, AttributeError):
                            protection_data["stage1_activated_at"] = None
                if "stage2_activated_at" in protection_data:
                    stage2_value = protection_data["stage2_activated_at"]
                    if stage2_value and isinstance(stage2_value, str):
                        try:
                            protection_data["stage2_activated_at"] = datetime.fromisoformat(
                                stage2_value
                            )
                        except (ValueError, AttributeError):
                            protection_data["stage2_activated_at"] = None
                return ProtectionState(**protection_data)
            return value

        converted_data = {}
        for key, value in data.items():
            converted_data[key] = convert_value(key, value)

        return cls(**converted_data)

    def to_json(self) -> str:
        """Serialize runtime state to JSON string."""
        return json.dumps(self.to_dict(), indent=2)

    @classmethod
    def from_json(cls, json_str: str) -> "RuntimeState":
        """Deserialize runtime state from JSON string."""
        data = json.loads(json_str)
        return cls.from_dict(data)

    def reset_for_new_day(self, new_day_key: str) -> None:
        """Reset daily counters for a new trading day."""
        self.day_key = new_day_key
        self.daily_locked = False
        self.daily_closed_profit = 0.0
        self.trades_today = 0
        # Note: last_entry_bar_time is NOT reset - it's bar-specific, not day-specific
